export const SbpmType = {
  SBPM_PROCESS_GROUP: 'SBPM_PROCESS_GROUP',
  SBPM_PROCESS_MODEL: 'SBPM_PROCESS_MODEL',
  SBPM_STANDARD_LAYER: 'SBPM_STANDARD_LAYER',
  SBPM_EXTENSION_LAYER: 'SBPM_EXTENSION_LAYER',
  SBPM_ABSTRACT_LAYER: 'SBPM_ABSTRACT_LAYER',
} as const;
